# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/victor/PycharmProjects/ECE-395-SeniorProj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/victor/PycharmProjects/ECE-395-SeniorProj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"python\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/PycharmProjects/ECE-395-SeniorProj/CMakeFiles /home/victor/PycharmProjects/ECE-395-SeniorProj//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/PycharmProjects/ECE-395-SeniorProj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BN_Sample

# Build rule for target.
BN_Sample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BN_Sample
.PHONY : BN_Sample

# fast build rule for target.
BN_Sample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/build
.PHONY : BN_Sample/fast

src/sampler/imagesampler.o: src/sampler/imagesampler.cpp.o
.PHONY : src/sampler/imagesampler.o

# target to build an object file
src/sampler/imagesampler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/imagesampler.cpp.o
.PHONY : src/sampler/imagesampler.cpp.o

src/sampler/imagesampler.i: src/sampler/imagesampler.cpp.i
.PHONY : src/sampler/imagesampler.i

# target to preprocess a source file
src/sampler/imagesampler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/imagesampler.cpp.i
.PHONY : src/sampler/imagesampler.cpp.i

src/sampler/imagesampler.s: src/sampler/imagesampler.cpp.s
.PHONY : src/sampler/imagesampler.s

# target to generate assembly for a file
src/sampler/imagesampler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/imagesampler.cpp.s
.PHONY : src/sampler/imagesampler.cpp.s

src/sampler/pyboost_cv2_converter.o: src/sampler/pyboost_cv2_converter.cpp.o
.PHONY : src/sampler/pyboost_cv2_converter.o

# target to build an object file
src/sampler/pyboost_cv2_converter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/pyboost_cv2_converter.cpp.o
.PHONY : src/sampler/pyboost_cv2_converter.cpp.o

src/sampler/pyboost_cv2_converter.i: src/sampler/pyboost_cv2_converter.cpp.i
.PHONY : src/sampler/pyboost_cv2_converter.i

# target to preprocess a source file
src/sampler/pyboost_cv2_converter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/pyboost_cv2_converter.cpp.i
.PHONY : src/sampler/pyboost_cv2_converter.cpp.i

src/sampler/pyboost_cv2_converter.s: src/sampler/pyboost_cv2_converter.cpp.s
.PHONY : src/sampler/pyboost_cv2_converter.s

# target to generate assembly for a file
src/sampler/pyboost_cv2_converter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/pyboost_cv2_converter.cpp.s
.PHONY : src/sampler/pyboost_cv2_converter.cpp.s

src/sampler/pyboost_cv3_converter.o: src/sampler/pyboost_cv3_converter.cpp.o
.PHONY : src/sampler/pyboost_cv3_converter.o

# target to build an object file
src/sampler/pyboost_cv3_converter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/pyboost_cv3_converter.cpp.o
.PHONY : src/sampler/pyboost_cv3_converter.cpp.o

src/sampler/pyboost_cv3_converter.i: src/sampler/pyboost_cv3_converter.cpp.i
.PHONY : src/sampler/pyboost_cv3_converter.i

# target to preprocess a source file
src/sampler/pyboost_cv3_converter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/pyboost_cv3_converter.cpp.i
.PHONY : src/sampler/pyboost_cv3_converter.cpp.i

src/sampler/pyboost_cv3_converter.s: src/sampler/pyboost_cv3_converter.cpp.s
.PHONY : src/sampler/pyboost_cv3_converter.s

# target to generate assembly for a file
src/sampler/pyboost_cv3_converter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/pyboost_cv3_converter.cpp.s
.PHONY : src/sampler/pyboost_cv3_converter.cpp.s

src/sampler/pyboost_cv4_converter.o: src/sampler/pyboost_cv4_converter.cpp.o
.PHONY : src/sampler/pyboost_cv4_converter.o

# target to build an object file
src/sampler/pyboost_cv4_converter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/pyboost_cv4_converter.cpp.o
.PHONY : src/sampler/pyboost_cv4_converter.cpp.o

src/sampler/pyboost_cv4_converter.i: src/sampler/pyboost_cv4_converter.cpp.i
.PHONY : src/sampler/pyboost_cv4_converter.i

# target to preprocess a source file
src/sampler/pyboost_cv4_converter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/pyboost_cv4_converter.cpp.i
.PHONY : src/sampler/pyboost_cv4_converter.cpp.i

src/sampler/pyboost_cv4_converter.s: src/sampler/pyboost_cv4_converter.cpp.s
.PHONY : src/sampler/pyboost_cv4_converter.s

# target to generate assembly for a file
src/sampler/pyboost_cv4_converter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/pyboost_cv4_converter.cpp.s
.PHONY : src/sampler/pyboost_cv4_converter.cpp.s

src/sampler/python_module.o: src/sampler/python_module.cpp.o
.PHONY : src/sampler/python_module.o

# target to build an object file
src/sampler/python_module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/python_module.cpp.o
.PHONY : src/sampler/python_module.cpp.o

src/sampler/python_module.i: src/sampler/python_module.cpp.i
.PHONY : src/sampler/python_module.i

# target to preprocess a source file
src/sampler/python_module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/python_module.cpp.i
.PHONY : src/sampler/python_module.cpp.i

src/sampler/python_module.s: src/sampler/python_module.cpp.s
.PHONY : src/sampler/python_module.s

# target to generate assembly for a file
src/sampler/python_module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/python_module.cpp.s
.PHONY : src/sampler/python_module.cpp.s

src/sampler/quasisampler_prototype.o: src/sampler/quasisampler_prototype.cpp.o
.PHONY : src/sampler/quasisampler_prototype.o

# target to build an object file
src/sampler/quasisampler_prototype.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/quasisampler_prototype.cpp.o
.PHONY : src/sampler/quasisampler_prototype.cpp.o

src/sampler/quasisampler_prototype.i: src/sampler/quasisampler_prototype.cpp.i
.PHONY : src/sampler/quasisampler_prototype.i

# target to preprocess a source file
src/sampler/quasisampler_prototype.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/quasisampler_prototype.cpp.i
.PHONY : src/sampler/quasisampler_prototype.cpp.i

src/sampler/quasisampler_prototype.s: src/sampler/quasisampler_prototype.cpp.s
.PHONY : src/sampler/quasisampler_prototype.s

# target to generate assembly for a file
src/sampler/quasisampler_prototype.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BN_Sample.dir/build.make CMakeFiles/BN_Sample.dir/src/sampler/quasisampler_prototype.cpp.s
.PHONY : src/sampler/quasisampler_prototype.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... BN_Sample"
	@echo "... src/sampler/imagesampler.o"
	@echo "... src/sampler/imagesampler.i"
	@echo "... src/sampler/imagesampler.s"
	@echo "... src/sampler/pyboost_cv2_converter.o"
	@echo "... src/sampler/pyboost_cv2_converter.i"
	@echo "... src/sampler/pyboost_cv2_converter.s"
	@echo "... src/sampler/pyboost_cv3_converter.o"
	@echo "... src/sampler/pyboost_cv3_converter.i"
	@echo "... src/sampler/pyboost_cv3_converter.s"
	@echo "... src/sampler/pyboost_cv4_converter.o"
	@echo "... src/sampler/pyboost_cv4_converter.i"
	@echo "... src/sampler/pyboost_cv4_converter.s"
	@echo "... src/sampler/python_module.o"
	@echo "... src/sampler/python_module.i"
	@echo "... src/sampler/python_module.s"
	@echo "... src/sampler/quasisampler_prototype.o"
	@echo "... src/sampler/quasisampler_prototype.i"
	@echo "... src/sampler/quasisampler_prototype.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

